### ISSUE TITLE
Integration do not create entity

### ISSUE THREAD

**Issue by zsbobbob** [eifinger/hass-foldingathomecontrol#13]
## Version of the custom_component
 2.0.3 HA 0.115.3

## Configuration

```yaml

Add your logs here.


## Describe the bug
A clear and concise description of what the bug is.
I am added the foldingathomecontroll via Hacs and after I try to add the integration on localshost, but I have the following error.

## Debug log

<!-- To enable debug logs check this https://www.home-assistant.io/components/logger/ -->

```text

2020-09-26 20:33:10 ERROR (MainThread) [homeassistant.util.logging] Exception in async_add_sensors when dispatching 'foldingathomecontrol_sensor_added_localhost': (['00'],)
Traceback (most recent call last):
  File "/config/custom_components/foldingathomecontrol/sensor.py", line 24, in async_add_sensors
    FoldingAtHomeControlSensor(
  File "/config/custom_components/foldingathomecontrol/sensor.py", line 56, in __init__
    super().__init__(client, slot_id)
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_device.py", line 16, in __init__
    self._device_name = f"{client.address} {client.slot_data[slot_id]['Description'].split(':')[0].upper()}: {slot_id}"  # pylint: disable=line-too-long

```

**Comment by eifinger** [comment]
Hi thank you for opening an issue.
The logs you posted here seem incomplete.

Could you please enable debug logs and post the output when you try to add the integration again?
Thank you!

**Comment by zsbobbob** [comment]
Hi,

Sorry, I was pretty sure that I have already answered, just recognised that not, sorry for the late answer.
This is the log file, where you can see debug messages.
[home-assistant.log](https://github.com/eifinger/hass-foldingathomecontrol/files/5361542/home-assistant.log)

I found this error which is connected to the foldingathome control.

`2020-10-11 19:10:17 ERROR (MainThread) [homeassistant.util.logging] Exception in async_add_sensors when dispatching 'foldingathomecontrol_sensor_added_localhost': (['00'],)
Traceback (most recent call last):
  File "/config/custom_components/foldingathomecontrol/sensor.py", line 24, in async_add_sensors
    FoldingAtHomeControlSensor(
  File "/config/custom_components/foldingathomecontrol/sensor.py", line 56, in __init__
    super().__init__(client, slot_id)
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_device.py", line 16, in __init__
    self._device_name = f"{client.address} {client.slot_data[slot_id]['Description'].split(':')[0].upper()}: {slot_id}"  # pylint: disable=line-too-long
KeyError: '00'`

**Comment by eifinger** [comment]
@zsbobbob I just released https://github.com/eifinger/hass-foldingathomecontrol/releases/tag/v2.0.4.
This should fix your issue

**Comment by zsbobbob** [comment]
Hi eifinger,

Updated the integration and tried to add foldingathome integration, but entities was not created. Services of the integration are available. The strange things that I can not see error in the log, when I am adding the integration to home assistant, se below.

[HA_debug_2020-11-06.log](https://github.com/eifinger/hass-foldingathomecontrol/files/5503114/HA_debug_2020-11-06.log)

Am I doing something wrong?

**Comment by eifinger** [comment]
Is your FoldingAtHome Instance running and folding?
I can see the following lines in the debug file:

```text
2020-11-06 19:54:18 DEBUG (MainThread) [FoldingAtHomeControl.serialconnection] Received welcome message: Welcome to the FAHClient command server.
2020-11-06 19:54:18 INFO (MainThread) [FoldingAtHomeControl.serialconnection] Got Cancelled
2020-11-06 19:54:18 DEBUG (MainThread) [FoldingAtHomeControl.foldingathomecontrol] Cleanup finished
```
The connection got created and immediately cancelled. I don't know why. And 2 seconds later it got created again and nothing happens after that;

```text
2020-11-06 19:54:20 DEBUG (MainThread) [FoldingAtHomeControl.serialconnection] Received welcome message: Welcome to the FAHClient command server.
```

**Comment by eifinger** [comment]
I will add additional logging and release a new version to better understand what is happening at your end

**Comment by zsbobbob** [comment]
That's great, it was my mistake, the instance was running, but not folding, after I started folding, the entities have been created in HA. 

Thanks for your help

**Comment by eifinger** [comment]
Thank you for taking the time and energy to help me fix it!
