### ISSUE TITLE
Folding@home on WIN10 add successfull but no entities

### ISSUE THREAD

**Issue by byackee** [eifinger/hass-foldingathomecontrol#27]
## Version of the custom_component
2.0.6

## Configuration

```yaml

Default configuration from integrations page.

```

## Describe the bug
I use folding@home on windows 10. When I add this integration I put ip adrress + Port without password (I tried with). The integration tell me add with success but I haven't any entities

## Debug log

```text

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/config/custom_components/foldingathomecontrol/__init__.py", line 64, in async_unload_entry
    await hass.data[DOMAIN][config_entry.entry_id].async_remove()
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_client.py", line 134, in async_remove
    await self._task
  File "/usr/local/lib/python3.8/site-packages/FoldingAtHomeControl/foldingathomecontrol.py", line 157, in start
    await self._try_parse_pyon_message_async()
  File "/usr/local/lib/python3.8/site-packages/FoldingAtHomeControl/foldingathomecontrol.py", line 204, in _try_parse_pyon_message_async
    await self._call_callbacks_async(message_type, json_object)
  File "/usr/local/lib/python3.8/site-packages/FoldingAtHomeControl/foldingathomecontrol.py", line 226, in _call_callbacks_async
    callback(message_type, message)
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_client.py", line 81, in data_received_callback
    self.handle_slots_data_received(data)
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_client.py", line 190, in handle_slots_data_received
    self.update_slots_data(slots_data)
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_client.py", line 215, in update_slots_data
    self.slot_data[slot["id"]]["Status"] = slot.get("status")
KeyError: '01'

```

**Comment by eifinger** [comment]
Hi @byackee thank you for opening an issue.
Is the traceback the only thing in your log in relation to this integration?

No entities showing up could mean that your Folding@Home Instance on Win10 is running but does not have any work assigned. Could that be the case?

The Traceback you attached shows that you removed the integration again when the error occurred. What where the exact steps you took which led to this Traceback?

Thank you!

**Comment by eifinger** [comment]
I just released [v2.0.7](https://github.com/eifinger/hass-foldingathomecontrol/releases/tag/v2.0.7).
Could you give it a try?

**Comment by byackee** [comment]
Hi,

thx for reactivity !! I appréciâtes that ;)
Version 2.0.7 not working too.

my logs:
´´
2021-04-10 17:53:07 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.2.17 for foldingathomecontrol
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/config/custom_components/foldingathomecontrol/__init__.py", line 64, in async_unload_entry
    await hass.data[DOMAIN][config_entry.entry_id].async_remove()
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_client.py", line 134, in async_remove
    await self._task
  File "/usr/local/lib/python3.8/site-packages/FoldingAtHomeControl/foldingathomecontrol.py", line 157, in start
    await self._try_parse_pyon_message_async()
  File "/usr/local/lib/python3.8/site-packages/FoldingAtHomeControl/foldingathomecontrol.py", line 204, in _try_parse_pyon_message_async
    await self._call_callbacks_async(message_type, json_object)
  File "/usr/local/lib/python3.8/site-packages/FoldingAtHomeControl/foldingathomecontrol.py", line 226, in _call_callbacks_async
    callback(message_type, message)
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_client.py", line 81, in data_received_callback
    self.handle_slots_data_received(data)
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_client.py", line 190, in handle_slots_data_received
    self.update_slots_data(slots_data)
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_client.py", line 215, in update_slots_data
    if self.slot_data[slot["id"]] is None:
KeyError: '01'
2021-04-10 17:55:03 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.2.17 for foldingathomecontrol
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/config/custom_components/foldingathomecontrol/__init__.py", line 64, in async_unload_entry
    await hass.data[DOMAIN][config_entry.entry_id].async_remove()
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_client.py", line 134, in async_remove
    await self._task
  File "/usr/local/lib/python3.8/site-packages/FoldingAtHomeControl/foldingathomecontrol.py", line 157, in start
    await self._try_parse_pyon_message_async()
  File "/usr/local/lib/python3.8/site-packages/FoldingAtHomeControl/foldingathomecontrol.py", line 204, in _try_parse_pyon_message_async
    await self._call_callbacks_async(message_type, json_object)
  File "/usr/local/lib/python3.8/site-packages/FoldingAtHomeControl/foldingathomecontrol.py", line 226, in _call_callbacks_async
    callback(message_type, message)
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_client.py", line 81, in data_received_callback
    self.handle_slots_data_received(data)
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_client.py", line 190, in handle_slots_data_received
    self.update_slots_data(slots_data)
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_client.py", line 215, in update_slots_data
    if self.slot_data[slot["id"]] is None:
KeyError: '01'
´´´

**Comment by eifinger** [comment]
Oh wow I'm stupid 😅 
Beginners mistake.
I'm currently on the road will release a fix as soon as I'm back on my pc

**Comment by byackee** [comment]
no worries:) Thx very much

**Comment by eifinger** [comment]
Okay 2.0,8 is out

**Comment by byackee** [comment]
YESSS!!!!!!!!! It is works!!!!!!! I have 2 entities!! 1 for cpu and 1 for gpu !!!

thank you very much again!!!!

**Comment by eifinger** [comment]
Thank you for reporting the issue and testing it.
Can we close this issue?

**Comment by byackee** [comment]
Yes I close it 😀
