### ISSUE TITLE
F@H Control not working anymore after Update

### ISSUE THREAD

**Issue by Od1waN** [eifinger/hass-foldingathomecontrol#32]
## Version of the custom_component

2.0.8
## Configuration

```yaml

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'dict' object has no attribute 'config_entry'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/foldingathomecontrol/services.py", line 46, in async_call_folding_at_home_control_service
    await async_pause_service(hass, service_data)
  File "/config/custom_components/foldingathomecontrol/services.py", line 98, in async_pause_service
    if hass.data[DOMAIN][config_entry].config_entry.data[CONF_ADDRESS] == address:
AttributeError: 'dict' object has no attribute 'config_entry'

[140369749619376] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 439, in handle_execute_script
    await script_obj.async_run(context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1195, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 341, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/foldingathomecontrol/services.py", line 46, in async_call_folding_at_home_control_service
    await async_pause_service(hass, service_data)
  File "/config/custom_components/foldingathomecontrol/services.py", line 98, in async_pause_service
    if hass.data[DOMAIN][config_entry].config_entry.data[CONF_ADDRESS] == address:
AttributeError: 'dict' object has no attribute 'config_entry'

```

## Describe the bug

After updating the Core the control isn't working and i become this error. I can not find the issue. I reinstalled F@H and F@H Control but not working.
My Automations:

```
  alias: F@H stoppen
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states("sensor.total_consumption_live")|int >= -100 }}'
  condition: []
  action:
  - service: foldingathomecontrol.pause
    data:
      address: localhost
      slot: ''
  mode: single
```

## Debug log

```text

Add your logs here.

```

**Comment by eifinger** [comment]
Thank you for reporting this issue. This is a leftover of the last Bugfix. I will fix this and release a new version in a few hours
