### ISSUE TITLE
Integration configured correctly but no entities

### ISSUE THREAD

**Issue by KingLudwig94** [eifinger/hass-foldingathomecontrol#71]
## Version of the custom_component
2.0.13

## Configuration

Default from integration page after auto-discovery notification.

## Describe the bug
The integration configures correctly but no entity shows up. Remote monitoring set up on Win10 and working from other devices in LAN via browser. The win10 FAH client is running and currently working.

## Debug log

No log during configuration.

If integration is removed this is the only error.

Logger: homeassistant.config_entries
Source: custom_components/foldingathomecontrol/foldingathomecontrol_client.py:150 
Integration: Folding@HomeControl (documentation, issues) 
First occurred: 11:44:04 (1 occurrences) 
Last logged: 11:44:04

Error unloading entry 192.168.1.37 for foldingathomecontrol
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 432, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/config/custom_components/foldingathomecontrol/__init__.py", line 68, in async_unload_entry
    await hass.data[DOMAIN][config_entry.entry_id][CLIENT].async_remove()
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_client.py", line 134, in async_remove
    await self._task
  File "/usr/local/lib/python3.9/site-packages/FoldingAtHomeControl/foldingathomecontrol.py", line 157, in start
    await self._try_parse_pyon_message_async()
  File "/usr/local/lib/python3.9/site-packages/FoldingAtHomeControl/foldingathomecontrol.py", line 204, in _try_parse_pyon_message_async
    await self._call_callbacks_async(message_type, json_object)
  File "/usr/local/lib/python3.9/site-packages/FoldingAtHomeControl/foldingathomecontrol.py", line 226, in _call_callbacks_async
    callback(message_type, message)
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_client.py", line 83, in data_received_callback
    self.handle_unit_data_received(data)
  File "/config/custom_components/foldingathomecontrol/foldingathomecontrol_client.py", line 150, in handle_unit_data_received
    self.slot_data[unit["slot"]]["Error"] = unit.get("error")
KeyError: '00'

**Comment by eifinger** [comment]
Hi thank you for reporting this issue.
Can you replicate that behaviour if you try to add the integration again after you removed it?

Could you also enable debug logging?

```yaml
logger:
  default: info
  logs:
    custom_components.FoldingAtHomeControl: debug
```

**Comment by eifinger** [comment]
I received no updates on this and there is a new version out. Please reopen the issue if it still persists. Thank you!
